version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: yeet_vip_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: yeet_vip
    ports:
      - "5432:5432"
    volumes:
      - yeet_vip_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  yeet_vip_postgres_data:
